### PR TITLE
added opacityControl-plugin

### LINKED ISSUE #24: Opacity Control
https://github.com/lizardtechblog/Leaflet.OpacityControls

### PR DESCRIPTION
**Pull request by trafficonese**
Adds support for the plugin:

- [https://github.com/lizardtechblog/Leaflet.OpacityControls]()

I changed and expanded the JS-code, so that it works without errors in R/Shiny. I also opened a [PR](https://github.com/lizardtechblog/Leaflet.OpacityControls/pull/10) at the original repo with those changes, but I'm not sure if it is still maintained since there are 2 other PR's waiting since 2015.

close #24

### CODE REVIEW

**Comment by tim-salabim** [comment]
There is already a [package on CRAN](https://cran.r-project.org/web/packages/leaflet.opacity/index.html) that provides access to this plugin.

Also, note that this repository (leaflet.extras) is currently not well maintained. I think @schloerke or someone else from RStudio currently only ensures that things here don't cause any trouble with leaflet releases, but there is no maintainence beyond that. 

In case you are interested in taking the lead on maintaining it, please let us/me know. Ultimately, I think @jcheng5 should somehow alert to how RStudio wants to handle the maintainence void here, but having someone who is willing to maintain it would be a good start...

**Comment by trafficonese** [comment]
@tim-salabim Thanks, I saw this package when I finished implementing it here. The implementation differs a bit and I modified the JS source to give the user more options and to sync the slider with the buttons.

I find it easier to maintain the JS code if it is in a separate .js file rather than in the `onRender` method, but that might just be a matter of taste. :)

Since I am just beginning to understand how all components (htmlWidgets, JS, R / Shiny) work together, I would be a little worried about being the maintainer of this package as some issues go beyond my understanding. 

Nonetheless, if no one else is found and the R/Shiny/Leaflet gurus help me fix bugs / add new features, I would take on the maintainer role.


Is @bhaskarvk not maintaining it anymore?

**Comment by tim-salabim** [comment]
No @bhaskarvk has left open source a long time ago unfortunately. He left me and the RStudio guys with admin rights for this package, but for me, same as you, most of the things here are beyond my skills, especially JS.

I sort of keep an eye on this repo as we use some parts from here in mapedit, but am too occupied with other package developments (mapview et al.) and don't want to take on leaflet.extras. 

I suggest we wait a while and see if RStudio has an opinion on this.

**Comment by jcheng5** [comment]
I don’t think anyone on our side is signed up to maintain this package, sorry. That’s why this is not and has never been under the rstudio GitHub org.

**Comment by jcheng5** [comment]
@tim-salabim what parts are you using in mapview/mapedit?

**Comment by tim-salabim** [comment]
@jcheng5 we use Leaflet.Draw plugin in mapedit.

**Comment by trafficonese** [comment]
I decided to transfer my open PRs with new features in a separate package [leaflet.extras2](https://github.com/trafficonese/leaflet.extras2).
I will try to integrate the remaining feature requests there to make maintenance of this package a little easier.

**Pull request closed without merging**
