### PR TITLE
Master

### PR DESCRIPTION
**Pull request by TrantorM**
leaflet choropleth maps with topojson support

### CODE REVIEW

**Comment by TrantorM** [comment]
Hello @bhaskarvk 
I would be happy, if I can contribute to the leaflet.extras package.

**Comment by bhaskarvk** [comment]
@TrantorM Thanks for the PR. However I do have a small request. This PR changes a lot more than just the topojson support, especially the references docs etc.
Would you be so kind to create a new PR with just the changes to the R and javascript code. Everything else I can do on my side, including updating NEWS/ DESCRIPTION (version increment)/DOCS etc.
That way it's much cleaner and easier for me.

Thanks

**Comment by bhaskarvk** [comment]
Thanks @TrantorM but that's not quite what I meant. You removed all other stuff, which still is problematic because if I merge this PR then these files will be deleted too.
What I wanted was just your R and JS files on top of my package. But for now don't worry, I'll take care of it from my side.
For now though I'm closing this PR as it's not merge-able with trunk.

**Comment by TrantorM** [comment]
I'm struggling a bit with the GitHub Desktop software. It's my first pull request... Thanks anyway @bhaskarvk.

**Comment by bhaskarvk** [comment]
No worries, I'll take care of it from my side and thanks for your contribution.

**Comment by bhaskarvk** [comment]
Hi I added the TopoJSON Choropleth support in 0.1.4.
Thank you so much for the code. You can find a working example at http://rpubs.com/bhaskarvk/topojson-choropleth

**Comment by TrantorM** [comment]
Looks good. Thank you for taking TopoJSON Choropleth support to the leaflet.extra package.

**Comment by bhaskarvk** [comment]
You're welcome, and while I was at it, I also added an option to highlight the polygons on hover. e.g. http://rpubs.com/bhaskarvk/topojson-choropleth has been updated to show the highlighting.

**Pull request closed without merging**
