### PR TITLE
add new draw options, fix for removeDrawToolbar

### LINKED ISSUE #148: removeDrawToolbar clearFeatures doesn't work anymore
`leaflet.extras::removeDrawToolbar(clearFeatures = TRUE)` doesn't seem to clear the features anymore. Anyone else notice this? I see that now there is "clear all features" option on the edit menu for draw. Was there ever a different way implemented to programmatically remove drawn features? Thanks.

### LINKED ISSUE #156: removeDrawToolbar() does not work.
removedrawtoolbar() does not seem to work  anymore, it used to work on older versions of the package.

### LINKED ISSUE #165: Uncaught TypeError: t.drawToolbar.removeFrom is not a function
Fairly minor error, but there is an error in the Javascript console which appears to be caused by the `removeDrawToolbar()` function. 

Here is a reproducible example:

```
library(shiny)
library(leaflet)
library(leaflet.extras)

lngs <- c(20, 23, 23)
lats <- c(21, 20, 24)

shinyApp(
  ui <- leafletOutput("map"), 
  
  server <- function(input, output, session){
    
    output$map <- renderLeaflet({
      leaflet() %>% 
        addTiles() %>% 
        addCircleMarkers(lng = lngs, lat = lats, layerId = 1:length(lats)) %>% 
        addDrawToolbar(targetGroup = "test", 
                       rectangleOptions = F, 
                       polylineOptions = F, 
                       markerOptions = F, 
                       editOptions = editToolbarOptions(selectedPathOptions = selectedPathOptions()), 
                       circleOptions = drawCircleOptions(shapeOptions = drawShapeOptions(clickable = T))) %>%
        removeDrawToolbar()
    })  # END RENDER LEAFLET 
    
    observeEvent(input$map_marker_click, {
      print(input$map_marker_click)
    })  
    
    observeEvent(input$map_draw_new_feature, {
      print(input$map_draw_new_feature)
    })
    
  })
```

If you open the app within Chrome and look at the developer console you can see the error:

image

I think this might be a case of just changing the call to the API function, as suggested in this SO post: https://stackoverflow.com/questions/39224307/leaflet-1-0-0-rc3-removefrom-method-causes-is-not-a-function-error

Hope that helps: doesn't seem to have major performance side effects but I don't know the inner-workings of leaflet that well!

### LINKED ISSUE #174: Customize text for tools of the draw tool bar
Hi everyone, is it possible to change the displayed text of the tools of the draw tool bar (leaflet map in a Shiny application)?
tools
I would like to display 'Finish', 'Delete last point', etc. in another language (i.e., in french).
I saw it can be done with `L.drawLocal` from `Leaflet.draw`, see [here](https://stackoverflow.com/questions/48661724/leaflet-draw-edit-control-custom-text) and [here](https://github.com/Leaflet/Leaflet.draw#customizing-language-and-text-in-leafletdraw) but I don't understand if I can do it in my R code.
Thanks a lot!

### PR DESCRIPTION
**Pull request by trafficonese**
Adds `handlersOptions` and `toolbarOptions` for `addDrawToolbar` which let you customize the drawing toolbar / tooltips.

This should close #174 

This should also close #148, close #156 and close #165 . 
The function `removeFrom` did not exist and was changed to `remove` and the typo `drawToobar` was corrected to `drawToolbar`

### CODE REVIEW

**Comment by claysa** [comment]
Sorry for my ignorance, I'm really new to github... Are these fixes ready to use with the package, or going to be merged with the main branch soon? When that happens will I only need to update the package to be able to use them?

Thanks so much for all your work on this!

**Comment by trafficonese** [comment]
Unfortunately the package is not well maintained at the moment. Please read the comments of #188. 

As soon as the PR is merged, you can install the new version with `remotes::install_github("bhaskarvk/leaflet.extras")` and once it is published to CRAN, you can run `install.packages("leaflet.extras")`.

If you want to try the PR already, you can install it with `remotes::install_github("bhaskarvk/leaflet.extras", ref = remotes::github_pull("184"))`

**Comment by claysa** [comment]
I'm trying the PR and so far so good, this is exactly what I was looking for. Thanks!

**Comment by nevilamos** [comment]
Hi, I have installed  the PRs above - I tried both 
rsion with remotes::install_github("bhaskarvk/leaflet.extras") and remotes::install_github("bhaskarvk/leaflet.extras", ref = remotes::github_pull("184"))

however  neither of them fixed the removeDrawToolbar , with or without clearfeatures =T.

do I understand correctly that using this PR it should be possible to remove the toolbar  and the drawn polyong featrue  using the following?


leafletProxy('mymap')%>%
            removeDrawToolbar(clearFeatures = T)

**Comment by trafficonese** [comment]
Yes, using this PR it should be possible to remove the draw-toolbar and the drawn shapes. This example works for me:

```
library(shiny)  
library(leaflet)
library(leaflet.extras)

ui <- fluidPage(
  leafletOutput("map"),
  actionButton("rm", "Remove Draw Toolbar")
)

server <- function(input, output, session) {
  output$map <- renderLeaflet({
    leaflet()  %>% 
      addTiles() %>% 
      addDrawToolbar()
  })
  
  observeEvent(input$rm, {
    leafletProxy('map')%>%
      removeDrawToolbar(clearFeatures = T)
  })
}
shinyApp(ui, server)
```

**Pull request closed without merging**
